import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const out = await build({
  entryPoints: ["src/app/app.ts"],
  bundle: true,
  format: "iife",
  target: ["es2020"],
  minify: true,
  write: false,
  legalComments: "none",
});
const js = out.outputFiles[0].text;
const shell = readFileSync("src/app/board.src.html", "utf8");

/**
 * A short content hash of the board, stamped into both the page and the server.
 *
 * The board is compiled into the server bundle and served at one fixed uri, so
 * "I redeployed and nothing changed" has two very different causes that look
 * identical: the deployment is still running old code, or the client is still
 * showing a cached copy of the resource. /health reports the build the server
 * holds and the board prints the build it is actually running, so the two can
 * be compared instead of guessed at.
 */
const stamped = shell.replace("/*__BUNDLE__*/", () => js);
const build_ = createHash("sha256").update(stamped).digest("hex").slice(0, 8);
const html = stamped.replace("__BUILD__", build_);

writeFileSync("src/app/board.html", html);
writeFileSync("src/app/board.generated.ts",
  `/* generated by scripts/build-app.mjs — do not edit */\n`
  + `export const BOARD_HTML = ${JSON.stringify(html)};\n`
  + `export const BOARD_BUILD = ${JSON.stringify(build_)};\n`);
console.log(`board.html  ${(html.length / 1024).toFixed(1)} kB  (bundle ${(js.length / 1024).toFixed(1)} kB)  build ${build_}`);
