import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";

const out = await build({
  entryPoints: ["src/app/app.ts"],
  bundle: true,
  format: "iife",
  target: ["es2020"],
  minify: true,
  write: false,
  legalComments: "none",
});
const js = out.outputFiles[0].text;
const shell = readFileSync("src/app/board.src.html", "utf8");
const html = shell.replace("/*__BUNDLE__*/", () => js);
writeFileSync("src/app/board.html", html);
writeFileSync("src/app/board.generated.ts",
  `/* generated by scripts/build-app.mjs — do not edit */\nexport const BOARD_HTML = ${JSON.stringify(html)};\n`);
console.log(`board.html  ${(html.length / 1024).toFixed(1)} kB  (bundle ${(js.length / 1024).toFixed(1)} kB)`);
